---

version: '3'

services:
  gvm-postgres:
    image: "securecompliance/postgres-gvm:latest"
    hostname: "postgres-gvm"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres-socket:/var/run/postgresql"
      - "postgres-data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_PASSWORD=gvm

  gvm-openvas:
    image: "securecompliance/openvas:latest"
    hostname: "openvas"
    restart: always
    ports:
      - "51000:51234"
    volumes:
      - "gvm-connect:/usr/local/var/run"
      - "ospd-socket:/var/run/ospd"
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
    # environment:
    #   - COMMUNITY_NVT_RSYNC_FEED=rsync://gvm-nvt-feed-server:/nvt-feed # Custom NVT server https://github.com/dgiorgio/gvm-nvt-feed-server

  gvm-gvmd:
    image: "securecompliance/gvmd:latest"
    hostname: "gvmd"
    restart: always
    ports:
      - "9390:9390"
    volumes:
      - "gvm-connect:/usr/local/var/run"
      - "ospd-socket:/var/run/ospd"
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      # - "/tmp/ssmtp=/etc/ssmtp" # optional - ssmtp config path
      - "postgres-socket:/var/run/postgresql"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - gvm-openvas
    depends_on:
      - gvm-openvas
      - gvm-postgres

  gvm-gsa:
    image: "securecompliance/gsa:latest"
    hostname: "gsa"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - gvm-gvmd
    depends_on:
      - gvm-gvmd
    environment:
      - GVMD_ADDRESS=gvm-gvmd
      - GVMD_PORT=9390
      - ENABLE_CRON=false

volumes:
  gvm-connect:
  gvm-data:
  openvas-data:
  ospd-socket:
  postgres-socket:
  postgres-data:
